
// QUE:-VOTING ELIGIBLE

var vote = prompt("enter your age")
if(vote>=18){
    alert("eligible for vote");
}else{
    alert("not eligible for vote");
    
}

// OUTPUT:- If true it gives "eligible for vote"
        //  If false it gives "not eligible for vote"


// QUE:- Eligible for marriage


var gender = prompt("enter your gender")
var age = prompt("enter your  age ")
if(age >= 21){
    alert("eligible for marriage");
}else{
    alert("not eligible for marriage");
}
if(age >= 18){
    alert("eligible for marriage");
}else{
    alert("not eligible for marriage");
}

//  OUTPUT:- IF CONDITION TRUE IT GIVES AS "ELIGIBLE FOR MARRIAGE". 
            //  IF CONDITION FALSE IT GIVES AS "NOT ELIGIBLE FOR MARRIAGE".  
             
// QUE:-LICENCE ELIGIBLE:-

var license = prompt("enter here license age ")
if(license >= 18){
    alert("eligible to apply license");
}else{
    alert("you are not eligible to apply license ");
} 

// OUTPUT:- IF True it gives "eligible to apply license"
        // IF False it gives "you are not eligible to apply licence"


// QUE:-EXAM ELIGIBLE

var Exam = prompt("enter here your percentage ")
if(Exam = 75){
    alert("you have better attendance to eligible for exam");
}else{
    alert("you have less attendence to eligible for exam");
}

// OUTPUT:- IF True it gives "you have better attendance to eligible for exam".
            // IF False it gives "you have less attendence to eligible for exam"



// QUE:-SENIOR CITIZEN

var senior = prompt("enter your age")
if(senior >=60){
    alert("The person qualifies for discount")
}else{
    alert("The person can't qualifies for discount")
}


// OUTPUT:;- IF True it gives "The person qualifies for discount"
            //  IF False it gives "The person can't qualifies for discount"

