


//  function abc(){
//     console.log(x);
//  }
//  abc( )
//  var x=400;
//  var x=200
//  abc( )


//  output:- undefined ,200


// let x = 10;
// if (true){
//     let x = 20;
// }
// console.log(x);

//  output:-- 10




function faa(a,b,c){
    arguments [0] = 10;
    console.log(a,arguments[0]);
    
}
faa(1,2,3);


// var a=20
// var b=30

// function parent(){
//     console.log(a+b)

//     var c=10
//     var b=25
//     function child(){
//         console.log(b-c)
//         console.log(a+b)
//     }child()
// }
// parent()


// output:- NaN , 15



// var b = 30
// function av(){
//     console.log(b)
// var b = 25
// console.log(b);

// }
// av()