// intro to dom:


let mani = document.getElementById("h1")
console.log(mani);
mani.style.color="blue"
mani.style.backgroundColor="lightgrey"
mani.style.padding="40px"
mani.style.borderRadius="1.5rem"
mani.style.boxShadow="10px  25px green"
mani.style.cursor="pointer"

function changetext(){
    mani.innerText="MANI,CURRENTLY PURSUING IN 1OK CODERS AS FULL STACK DEVELOPER"

}

let chintu = document.getElementById("h2")
console.log(chintu);
chintu.style.color="blue"
chintu.style.backgroundColor="lightgrey"
chintu.style.padding="40px"
chintu.style.borderRadius="1.5rem"
chintu.style.boxShadow="10px  25px green"
chintu.style.cursor="pointer"

function changetextdbl(){
    chintu.innerText="MANI,CURRENTLY PURSUING IN 1OK CODERS AS FULL STACK DEVELOPER"

}

let sagar = document.getElementById("h3")
console.log(sagar);
sagar.style.color="blue"
sagar.style.backgroundColor="lightgrey"
sagar.style.padding="40px"
sagar.style.borderRadius="1.5rem"
sagar.style.boxShadow="10px  25px green"
sagar.style.cursor="pointer"

function changetextover(){
    sagar.innerText="MANI,CURRENTLY PURSUING IN 1OK CODERS AS FULL STACK DEVELOPER"

}
