
// FOR LOOP:-

// var arr=["vamsi","mani","sagar"];
// for (var b=0; b<arr.length; b++){
//     console.log(arr[b])
// }

// OUTPUT:- vamsi
//          mani
//          sagar
  
//   Reverse of array:-

// var arr=["vamsi","mani","sagar"];
// for (var b=arr.length-1; b>=0; b--){
//     console.log(arr[b])
// }

// OUTPUT:- sagar 
//          mani 
//          vamsi

// even and odd numbers:-

// var b=[10,11,12,13,14,15,16]
// for(var i=0; i<b.length;i++){
//     if(b[i]%2==0){
//     console.log(b[i],"even")
// }else{
//     console.log(b[i],'odd')
// }
// }

// sum of even and odd Numbers:-

// var b=[2,3,4,5,6,7,8,9]
// var sumeven=0;
// var sumodd=0;
// for (var i=0 ; i<b.length ; i++){
//     if (b[i]% 2==0){
//         sumeven = sumeven+b[i]
//     }else{
//         sumodd = sumodd+b[i]
        
//     }
// }
// console.log(sumeven,"even")
// console.log(sumodd,"odd");

// product of even and odd numbers:_

// var b=[2,3,4,5,6,7,8,9]
// var producteven=1;
// var productodd=1;
// for (var i=0 ; i<b.length ; i++){
//     if (b[i]% 2==0){
//         producteven = producteven*b[i]
//     }else{
//         productodd = productodd*b[i]
        
//     }
// }
// console.log(producteven,"even")
// console.log(productodd,"odd");


    // WHILE LOOP

// var a=0;
// while(a<=20){
//     console.log(a);
//     a++
    
// }

// to get ann odd num:_
// var a=[2,4,6,8,10,13,15]
// var i=0
// while(i<a.length){
//     if(a[i]%2==1){
//         console.log(a[i])
//     }
//     i++
// }

// to get even numbers:-

// var a=[2,4,6,8,10,13,15]
// var i=0
// while(i<a.length){
//     if(a[i]%2==0){
//         console.log(a[i])
//     }
//     i++
// }
 
//  DO WHILE LOOP

// var a=10
// do{
//     a--
//     console.log(a);
    
// }while(a==1)


// var a=9
// do{
//     a++
//     console.log(a);
    
// }while(a==0)
